### ISSUE TITLE
support for 1.4 stable series?

### ISSUE THREAD

**Issue by akohlsmith** [bitherder/redmine_markdown_formatter#6]
Is this plugin still being maintained? Which version of rdiscount is needed? When I try to install the plugin on a 1.4.2stable Redmine install with rdiscount 1.6.8 (and rpeg-markdown 1.4.6) I get a rake error stating that it can't load the file rdiscount. Freenode #redmine suggested that this patch is no longer compatible with the newer versions of Redmine or perhaps the version of rdiscount that I have installed.

Unfortunately I'm a pretty green ruby newbie and have not been successful in figuring this out on my own.

**Comment by axolx** [comment]
afaik the plugin should work on 1.4. rdiscount is a required gem by the plugin so you'll have to install it.

**Comment by fly2never** [comment]
me too,rdiscount 1.6.8 doesn't work

**Comment by bashhu** [comment]
When I try to install the plugin on a  2.5.0.stable Redmine install with  2.5.0.stable (and rpeg-markdown-1.4.6)Successfully installed ,but stating that it can't load the file rdiscount. 

/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- rdiscount (LoadError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`block in require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
    from /opt/redmine/plugins/redmine_markdown_formatter/lib/redmine_markdown_formatter/wiki_formatter.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:359:in`require_or_load'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:502:in `load_missing_constant'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:192:in`block in const_missing'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:190:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:190:in`const_missing'
    from /opt/redmine/plugins/redmine_markdown_formatter/init.rb:14:in `block in <top (required)>'
    from /opt/redmine/lib/redmine/plugin.rb:73:in`instance_eval'
    from /opt/redmine/lib/redmine/plugin.rb:73:in `register'
    from /opt/redmine/plugins/redmine_markdown_formatter/init.rb:8:in`<top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`block in require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
    from /opt/redmine/lib/redmine/plugin.rb:133:in `block in load'
    from /opt/redmine/lib/redmine/plugin.rb:124:in`each'
    from /opt/redmine/lib/redmine/plugin.rb:124:in `load'
    from /opt/redmine/config/initializers/30-redmine.rb:19:in`<top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `load'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in`block in load'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in`load'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/engine.rb:592:in`each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/engine.rb:592:in `block in <class:Engine>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/initializable.rb:30:in`instance_exec'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/initializable.rb:54:in`run_initializers'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /opt/redmine/config/environment.rb:14:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
    from /opt/redmine/config.ru:3:in`block in <main>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in`initialize'
    from /opt/redmine/config.ru:in `new'
    from /opt/redmine/config.ru:in`<main>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:40:in`parse_file'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands/server.rb:46:in`app'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
    from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/server.rb:254:in`start'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands/server.rb:70:in `start'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands.rb:55:in`block in <top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands.rb:50:in `tap'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands.rb:50:in`<top (required)>'
    from /opt/redmine/script/rails:6:in `require'
    from /opt/redmine/script/rails:6:in`<main>'

what's wrong with me ?
___
